// src/components/lp/LandingPageForm.tsx
'use client'

import React, { useState, useRef, useEffect, useCallback } from 'react'
import { type SubmitHandler, useForm, useWatch } from 'react-hook-form'
import { z } from 'zod'
import { zodResolver } from '@hookform/resolvers/zod'
import { motion, AnimatePresence } from 'motion/react'
import Script from 'next/script'
import { sendEmail } from '@/app/actions/sendEmail'
import { trackEvent } from '@/lib/analytics/events'

const schema = z.object({
    firstName: z.string().min(2, { error: 'Required' }),
    lastName: z.string().min(2, { error: 'Required' }),
    email: z.email({ error: 'Invalid email' }),
    websiteUrl: z.string().optional(),
    message: z.string().min(2, { error: 'Required' }),
    turnstileToken: z.string().min(1, { error: 'Bot verification required' }),
})

type Inputs = z.infer<typeof schema>

const shakeVariants = {
    error: { x: [0, -4, 4, -4, 4, 0], transition: { duration: 0.35 } },
}

function Field({
    label,
    error,
    children,
    span2 = false,
}: {
    label: string
    error?: string
    children: React.ReactNode
    span2?: boolean
}) {
    return (
        <motion.div
            animate={error ? 'error' : ''}
            variants={shakeVariants}
            className={`space-y-2${span2 ? ' md:col-span-2' : ''}`}
        >
            <div className="flex items-baseline justify-between">
                <label className="text-xs font-bold uppercase tracking-widest text-text-muted">
                    {label}
                </label>
                {error && (
                    <span role="alert" className="text-xs text-red-400">
                        {error}
                    </span>
                )}
            </div>
            {children}
        </motion.div>
    )
}

const baseInput =
    'w-full rounded-xl border bg-surface px-4 py-3 text-sm text-text placeholder:text-text-muted-2 transition-colors focus:outline-none'
const inputOk = 'border-border focus:border-border-strong'
const inputErr = 'border-red-500/50 focus:border-red-500/70'

export function LandingPageForm({
    heading,
    ctaCopy,
    campaignTag,
    gadsConversionId,
    gadsConversionLabel,
}: {
    heading?: string
    ctaCopy?: string
    campaignTag: string
    gadsConversionId?: string
    gadsConversionLabel?: string
}) {
    const [isSuccess, setIsSuccess] = useState(false)
    const [serverError, setServerError] = useState<string | null>(null)
    const [formTouched, setFormTouched] = useState(false)
    const turnstileRef = useRef<HTMLDivElement>(null)
    const widgetIdRef = useRef<string | null>(null)

    const {
        register,
        handleSubmit,
        reset,
        setValue,
        control,
        formState: { errors, isSubmitting },
    } = useForm<Inputs>({
        resolver: zodResolver(schema),
        defaultValues: { turnstileToken: '' },
    })

    const turnstileToken = useWatch({ control, name: 'turnstileToken' })

    useEffect(() => {
        return () => {
            if (widgetIdRef.current && window.turnstile) {
                window.turnstile.remove(widgetIdRef.current)
                widgetIdRef.current = null
            }
        }
    }, [])

    const onSubmit = useCallback<SubmitHandler<Inputs>>(
        async (data) => {
            setServerError(null)
            trackEvent('contact_form_submit', { campaign: campaignTag })

            const { turnstileToken: token, ...formData } = data
            const result = await sendEmail({ ...formData, campaignTag }, token)

            if (result.success) {
                setIsSuccess(true)
                trackEvent('contact_form_success', { campaign: campaignTag })

                // Fire Google Ads conversion
                if (gadsConversionId && gadsConversionLabel && typeof window.gtag === 'function') {
                    window.gtag('event', 'conversion', {
                        send_to: `${gadsConversionId}/${gadsConversionLabel}`,
                    })
                }

                reset()
                if (widgetIdRef.current && window.turnstile) {
                    window.turnstile.reset(widgetIdRef.current)
                }
            } else {
                setServerError(result.error ?? 'Something went wrong. Please try again.')
                trackEvent('contact_form_error', { error: result.error ?? 'unknown' })
            }
        },
        [reset, campaignTag, gadsConversionId, gadsConversionLabel]
    )

    return (
        <>
            <div className="space-y-6">
                {heading && (
                    <h2 className="text-2xl font-extrabold tracking-tight text-text">
                        {heading}
                    </h2>
                )}

                <AnimatePresence mode="wait">
                    {!isSuccess ? (
                        <motion.div
                            key="form"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            transition={{ duration: 0.3 }}
                        >
                            <form
                                onSubmit={(e) => handleSubmit(onSubmit)(e)}
                                onFocus={() => {
                                    if (!formTouched) setFormTouched(true)
                                }}
                                noValidate
                                className="rounded-3xl border border-border bg-surface p-8 md:p-10 space-y-6"
                            >
                                <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
                                    <Field label="First name" error={errors.firstName?.message}>
                                        <input
                                            {...register('firstName')}
                                            placeholder="Brian"
                                            aria-invalid={!!errors.firstName}
                                            className={`${baseInput} ${errors.firstName ? inputErr : inputOk}`}
                                        />
                                    </Field>

                                    <Field label="Last name" error={errors.lastName?.message}>
                                        <input
                                            {...register('lastName')}
                                            placeholder="Smith"
                                            aria-invalid={!!errors.lastName}
                                            className={`${baseInput} ${errors.lastName ? inputErr : inputOk}`}
                                        />
                                    </Field>

                                    <Field label="Email" error={errors.email?.message} span2>
                                        <input
                                            {...register('email')}
                                            type="email"
                                            placeholder="hello@yourbusiness.com"
                                            aria-invalid={!!errors.email}
                                            className={`${baseInput} ${errors.email ? inputErr : inputOk}`}
                                        />
                                    </Field>

                                    <Field label="Current website (optional)" error={errors.websiteUrl?.message} span2>
                                        <input
                                            {...register('websiteUrl')}
                                            type="url"
                                            placeholder="https://yourbusiness.com"
                                            className={`${baseInput} ${inputOk}`}
                                        />
                                    </Field>

                                    <Field label="What are you looking for?" error={errors.message?.message} span2>
                                        <textarea
                                            {...register('message')}
                                            rows={4}
                                            placeholder="Tell me a bit about your business and what you need. A few sentences is enough."
                                            aria-invalid={!!errors.message}
                                            className={`${baseInput} ${errors.message ? inputErr : inputOk} resize-none`}
                                        />
                                    </Field>
                                </div>

                                <div>
                                    <div ref={turnstileRef} />
                                </div>

                                {serverError && (
                                    <div role="alert" className="rounded-xl border border-red-500/30 bg-red-500/5 px-4 py-3">
                                        <p className="text-sm text-red-400">{serverError}</p>
                                    </div>
                                )}

                                <button
                                    type="submit"
                                    disabled={isSubmitting || !turnstileToken}
                                    className="w-full rounded-full bg-text py-4 text-sm font-bold text-bg transition hover:opacity-90 disabled:opacity-40 disabled:cursor-not-allowed"
                                >
                                    {isSubmitting ? 'Sending…' : (ctaCopy ?? 'Send my info')}
                                </button>
                            </form>
                        </motion.div>
                    ) : (
                        <motion.div
                            key="success"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ duration: 0.3 }}
                            className="rounded-3xl border border-border bg-surface p-12 text-center space-y-6"
                        >
                            <div className="mx-auto flex size-14 items-center justify-center rounded-full border border-border-strong bg-bg">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="text-text">
                                    <polyline points="20 6 9 17 4 12" />
                                </svg>
                            </div>
                            <div className="space-y-2">
                                <h2 className="text-2xl font-extrabold tracking-tight text-text">
                                    Got it — we&#39;ll be in touch
                                </h2>
                                <p className="text-text-muted">
                                    Expect a reply within one business day.
                                </p>
                            </div>
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>

            {formTouched && (
                <Script
                    src="https://challenges.cloudflare.com/turnstile/v0/api.js"
                    strategy="afterInteractive"
                    onReady={() => {
                        if (turnstileRef.current && window.turnstile && !widgetIdRef.current) {
                            widgetIdRef.current = window.turnstile.render(turnstileRef.current, {
                                sitekey: process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY!,
                                theme: 'dark',
                                callback: (token: string) =>
                                    setValue('turnstileToken', token, { shouldValidate: true }),
                                'expired-callback': () =>
                                    setValue('turnstileToken', '', { shouldValidate: true }),
                                'error-callback': () =>
                                    setValue('turnstileToken', '', { shouldValidate: true }),
                            })
                        }
                    }}
                />
            )}
        </>
    )
}

// src/components/interactive/LandingPageForm.svelte
<script lang="ts">
  import { onMount } from 'svelte';

  export let heading: string | undefined;
  export let ctaCopy: string | undefined;
  export let campaignTag: string;
  export let gadsConversionId: string | undefined;
  export let gadsConversionLabel: string | undefined;

  let firstName = '';
  let lastName = '';
  let email = '';
  let websiteUrl = '';
  let message = '';
  let turnstileToken = '';
  let submitting = false;
  let success = false;
  let error = '';

  onMount(() => {
    const sitekey =
      import.meta.env.PUBLIC_TURNSTILE_SITE_KEY ??
      import.meta.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY;
    if (!sitekey) return;

    const render = () => {
      const el = document.getElementById('lp-turnstile');
      if (!el || !(window as any).turnstile) return;
      (window as any).turnstile.render(el, {
        sitekey,
        theme: 'dark',
        callback: (token: string) => (turnstileToken = token),
        'expired-callback': () => (turnstileToken = ''),
        'error-callback': () => (turnstileToken = ''),
      });
    };

    if ((window as any).turnstile) return render();
    const script = document.createElement('script');
    script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js';
    script.async = true;
    script.defer = true;
    script.onload = render;
    document.head.appendChild(script);
  });

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    error = '';
    if (firstName.trim().length < 2 || lastName.trim().length < 2 || !email.includes('@') || message.trim().length < 2) {
      error = 'Please complete all required fields.';
      return;
    }

    submitting = true;
    try {
      const response = await fetch('/api/contact', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ firstName, lastName, email, websiteUrl, message, campaignTag, turnstileToken }),
      });
      const result = await response.json();
      if (!response.ok || !result.success) throw new Error(result.error || 'Could not send your message.');

      success = true;
      if (gadsConversionId && gadsConversionLabel && typeof (window as any).gtag === 'function') {
        (window as any).gtag('event', 'conversion', { send_to: `${gadsConversionId}/${gadsConversionLabel}` });
      }
    } catch (err) {
      error = err instanceof Error ? err.message : 'Could not send your message.';
    } finally {
      submitting = false;
    }
  }
</script>

<div class="space-y-6">
  {#if heading}<h2 class="text-2xl font-extrabold tracking-tight text-text">{heading}</h2>{/if}
  {#if success}
    <div class="rounded-3xl border border-border bg-surface p-12 text-center space-y-3" role="status" aria-live="polite">
      <h2 class="text-2xl font-extrabold text-text">Got it — we'll be in touch</h2>
      <p class="text-text-muted">Expect a reply within one business day.</p>
    </div>
  {:else}
    <form onsubmit={submit} novalidate class="rounded-3xl border border-border bg-surface p-8 md:p-10 space-y-6">
      <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
        <div class="space-y-2">
          <label for="lp-first-name" class="text-xs font-bold uppercase tracking-widest text-text-muted">First name</label>
          <input id="lp-first-name" bind:value={firstName} autocomplete="given-name" required aria-required="true" class="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm text-text" placeholder="Brian" />
        </div>
        <div class="space-y-2">
          <label for="lp-last-name" class="text-xs font-bold uppercase tracking-widest text-text-muted">Last name</label>
          <input id="lp-last-name" bind:value={lastName} autocomplete="family-name" required aria-required="true" class="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm text-text" placeholder="Smith" />
        </div>
        <div class="space-y-2 md:col-span-2">
          <label for="lp-email" class="text-xs font-bold uppercase tracking-widest text-text-muted">Email</label>
          <input id="lp-email" bind:value={email} type="email" autocomplete="email" required aria-required="true" class="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm text-text" placeholder="hello@yourbusiness.com" />
        </div>
        <div class="space-y-2 md:col-span-2">
          <label for="lp-website" class="text-xs font-bold uppercase tracking-widest text-text-muted">Current website <span class="font-normal normal-case">(optional)</span></label>
          <input id="lp-website" bind:value={websiteUrl} type="url" autocomplete="url" class="w-full rounded-xl border border-border bg-surface px-4 py-3 text-sm text-text" placeholder="https://yourbusiness.com" />
        </div>
        <div class="space-y-2 md:col-span-2">
          <label for="lp-message" class="text-xs font-bold uppercase tracking-widest text-text-muted">What are you looking for?</label>
          <textarea id="lp-message" bind:value={message} rows="4" required aria-required="true" class="w-full resize-none rounded-xl border border-border bg-surface px-4 py-3 text-sm text-text" placeholder="Tell me a bit about your business and what you need."></textarea>
        </div>
      </div>
      <div id="lp-turnstile"></div>
      {#if error}<p role="alert" class="text-sm text-red-400">{error}</p>{/if}
      <button type="submit" disabled={submitting} class="w-full rounded-full bg-text py-4 text-sm font-bold text-bg disabled:cursor-not-allowed disabled:opacity-40">
        {submitting ? 'Sending…' : (ctaCopy ?? 'Send my info')}
      </button>
    </form>
  {/if}
</div>
